package blockchain

val namesList = listOf(
    "Emma",
    "Olivia",
    "Ava",
    "Isabella",
    "Sophia",
    "Mia",
    "Charlotte",
    "Amelia",
    "Harper",
    "Evelyn",
    "Abigail",
    "Emily",
    "Elizabeth",
    "Mila",
    "Ella",
    "Avery",
    "Sofia",
    "Camila",
    "Aria",
    "Scarlett",
    "Victoria",
    "Madison",
)

val messagesList = listOf(
    "Good morning!",
    "How are you?",
    "What are you up to today?",
    "Have a great day!",
    "Talk to you later.",
    "Good night!",
    "What's new?",
    "How's your day going?",
    "What's up?",
    "How's everything?",
    "How's life?",
    "What have you been up to lately?",
    "Long time no see!",
    "It's been a while!",
    "How have you been?",
    "What are your plans for the weekend?",
    "How was your weekend?",
    "Did you do anything fun over the weekend?",
    "What did you do over the weekend?",
    "How was your day?",
    "Did you have a good day?",
    "What did you do today?",
    "How was work today?",
    "How was school today?",
    "Did anything interesting happen at work today?",
    "Did anything interesting happen at school today?",
    "How's the weather where you are?",
    "Is it snowy where you are?",
    "Is it rainy where you are?",
    "Is it cold where you are?",
    "Is it hot where you are?",
    "What's the temperature like where you are?",
    "Are you enjoying the weather?",
    "Do you have any plans for tonight?",
    "Are you doing anything fun tonight?",
    "What are you having for dinner tonight?",
    "Did you eat anything good today?",
    "Have you tried any new restaurants lately?",
    "Do you have any recommendations for good restaurants in your area?",
    "Have you seen any good movies lately?",
    "Have you watched any good TV shows lately?",
    "Have you read any good books lately?",
    "Have you listened to any good music lately?",
    "Do you have any recommendations for good music?",
    "Do you have any recommendations for good books?",
    "Do you have any recommendations for good TV shows?",
    "Do you have any recommendations for good movies?",
    "Have you been on any trips lately?",
    "Do you have any upcoming travel plans?",
    "Where would you like to go on vacation next?",
    "Have you been to any cool places recently?",
    "Do you have any fun stories from your travels?",
    "Are you into sports at all? Which ones do you follow or play",
)
